In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv(r"C:\Users\jyoth\Downloads\archive (22)\superstore.csv")

In [3]:
df.head(3)

,Category,City,Country,Customer.ID,Customer.Name,Discount,Market,记录数,Order.Date,Order.ID,...,Sales,Segment,Ship.Date,Ship.Mode,Shipping.Cost,State,Sub.Category,Year,Market2,weeknum
0,Office Supplies,Los Angeles,United States,LS-172304,Lycoris Saunders,0.0,US,1,2011-01-07 00:00:00.000,CA-2011-130813,...,19,Consumer,2011-01-09 00:00:00.000,Second Class,4.37,California,Paper,2011,North America,2
1,Office Supplies,Los Angeles,United States,MV-174854,Mark Van Huff,0.0,US,1,2011-01-21 00:00:00.000,CA-2011-148614,...,19,Consumer,2011-01-26 00:00:00.000,Standard Class,0.94,California,Paper,2011,North America,4
2,Office Supplies,Los Angeles,United States,CS-121304,Chad Sievert,0.0,US,1,2011-08-05 00:00:00.000,CA-2011-118962,...,21,Consumer,2011-08-09 00:00:00.000,Standard Class,1.81,California,Paper,2011,North America,32

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 51290 entries, 0 to 51289
Data columns (total 27 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Category        51290 non-null  object
 1   City            51290 non-null  object
 2   Country         51290 non-null  object
 3   Customer.ID     51290 non-null  object
 4   Customer.Name   51290 non-null  object
 5   Discount        51290 non-null  float64
 6   Market          51290 non-null  object
 7   记录数             51290 non-null  int64
 8   Order.Date      51290 non-null  object
 9   Order.ID        51290 non-null  object
 10  Order.Priority  51290 non-null  object
 11  Product.ID      51290 non-null  object
 12  Product.Name    51290 non-null  object
 13  Profit          51290 non-null  float64
 14  Quantity        51290 non-null  int64
 15  Region          51290 non-null  object
 16  Row.ID          51290 non-null  int64
 17  Sales           51290 non-null  int64
 18  Segment         51290 non-null  object
 19  Ship.Date       51290 non-null  object
 20  Ship.Mode       51290 non-null  object
 21  Shipping.Cost   51290 non-null  float64
 22  State           51290 non-null  object
 23  Sub.Category    51290 non-null  object
 24  Year            51290 non-null  int64
 25  Market2         51290 non-null  object
 26  weeknum         51290 non-null  int64
dtypes: float64(3), int64(6), object(18)
memory usage: 10.6+ MB

In [5]:
df.shape

(51290, 27)

# cols to drop

记录数
Row.ID
Customer.ID
Order.ID
Product.ID
Market
Market2
Order.Priority
Ship.Mode
Ship.Date
Shipping.Cost
Year
weeknum
Discount   (optional – drop for now to keep it simple)

In [6]:
df.describe()

,Discount,记录数,Profit,Quantity,Row.ID,Sales,Shipping.Cost,Year,weeknum
count,51290.000000,51290.0,51290.000000,51290.000000,51290.00000,51290.000000,51290.000000,51290.000000,51290.000000
mean,0.142908,1.0,28.610982,3.476545,25645.50000,246.498440,26.375818,2012.777208,31.287112
std,0.212280,0.0,174.340972,2.278766,14806.29199,487.567175,57.296810,1.098931,14.429795
min,0.000000,1.0,-6599.978000,1.000000,1.00000,0.000000,0.002000,2011.000000,1.000000
25%,0.000000,1.0,0.000000,2.000000,12823.25000,31.000000,2.610000,2012.000000,20.000000
50%,0.000000,1.0,9.240000,3.000000,25645.50000,85.000000,7.790000,2013.000000,33.000000
75%,0.200000,1.0,36.810000,5.000000,38467.75000,251.000000,24.450000,2014.000000,44.000000
max,0.850000,1.0,8399.976000,14.000000,51290.00000,22638.000000,933.570000,2014.000000,53.000000

In [7]:
df.drop('记录数', axis=1, inplace=True)

In [8]:
df.columns

Index(['Category', 'City', 'Country', 'Customer.ID', 'Customer.Name',
       'Discount', 'Market', 'Order.Date', 'Order.ID', 'Order.Priority',
       'Product.ID', 'Product.Name', 'Profit', 'Quantity', 'Region', 'Row.ID',
       'Sales', 'Segment', 'Ship.Date', 'Ship.Mode', 'Shipping.Cost', 'State',
       'Sub.Category', 'Year', 'Market2', 'weeknum'],
      dtype='object')

In [9]:
df.drop(['Row.ID','Customer.ID','Order.ID','Product.ID','Market','Market2','Order.Priority','Ship.Mode','Ship.Date','Shipping.Cost','Year','weeknum','Discount'], axis=1, inplace=True)

In [10]:
df.columns

Index(['Category', 'City', 'Country', 'Customer.Name', 'Order.Date',
       'Product.Name', 'Profit', 'Quantity', 'Region', 'Sales', 'Segment',
       'State', 'Sub.Category'],
      dtype='object')

In [11]:
df.shape

(51290, 13)

# check for null values

In [12]:
df.isnull().sum() # no null values

Category         0
City             0
Country          0
Customer.Name    0
Order.Date       0
Product.Name     0
Profit           0
Quantity         0
Region           0
Sales            0
Segment          0
State            0
Sub.Category     0
dtype: int64

# check for duplicates

In [13]:
df.duplicated().sum()

np.int64(9)

In [14]:
df = df.drop_duplicates()

In [15]:
df.duplicated().sum()

np.int64(0)

In [16]:
df.columns = df.columns.str.replace('.', '_')
df.columns = df.columns.str.replace(' ', '_')
df.columns = df.columns.str.lower()

In [17]:
df.columns

Index(['category', 'city', 'country', 'customer_name', 'order_date',
       'product_name', 'profit', 'quantity', 'region', 'sales', 'segment',
       'state', 'sub_category'],
      dtype='object')

In [18]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 51281 entries, 0 to 51289
Data columns (total 13 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   category       51281 non-null  object
 1   city           51281 non-null  object
 2   country        51281 non-null  object
 3   customer_name  51281 non-null  object
 4   order_date     51281 non-null  object
 5   product_name   51281 non-null  object
 6   profit         51281 non-null  float64
 7   quantity       51281 non-null  int64
 8   region         51281 non-null  object
 9   sales          51281 non-null  int64
 10  segment        51281 non-null  object
 11  state          51281 non-null  object
 12  sub_category   51281 non-null  object
dtypes: float64(1), int64(2), object(10)
memory usage: 5.5+ MB

In [19]:
df.head()

,category,city,country,customer_name,order_date,product_name,profit,quantity,region,sales,segment,state,sub_category
0,Office Supplies,Los Angeles,United States,Lycoris Saunders,2011-01-07 00:00:00.000,Xerox 225,9.3312,3,West,19,Consumer,California,Paper
1,Office Supplies,Los Angeles,United States,Mark Van Huff,2011-01-21 00:00:00.000,"Wirebound Service Call Books, 5 1/2"" x 4""",9.2928,2,West,19,Consumer,California,Paper
2,Office Supplies,Los Angeles,United States,Chad Sievert,2011-08-05 00:00:00.000,"Adams Phone Message Book, Professional, 400 Me...",9.8418,3,West,21,Consumer,California,Paper
3,Office Supplies,Los Angeles,United States,Chad Sievert,2011-08-05 00:00:00.000,Xerox 1913,53.2608,2,West,111,Consumer,California,Paper
4,Office Supplies,Los Angeles,United States,Arthur Prichep,2011-09-29 00:00:00.000,Xerox 223,3.1104,1,West,6,Consumer,California,Paper

In [20]:
# converting datatype

In [21]:
df['order_date'] = pd.to_datetime(df['order_date'])

In [22]:
df['order_date'] = df['order_date'].dt.date

In [23]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 51281 entries, 0 to 51289
Data columns (total 13 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   category       51281 non-null  object
 1   city           51281 non-null  object
 2   country        51281 non-null  object
 3   customer_name  51281 non-null  object
 4   order_date     51281 non-null  object
 5   product_name   51281 non-null  object
 6   profit         51281 non-null  float64
 7   quantity       51281 non-null  int64
 8   region         51281 non-null  object
 9   sales          51281 non-null  int64
 10  segment        51281 non-null  object
 11  state          51281 non-null  object
 12  sub_category   51281 non-null  object
dtypes: float64(1), int64(2), object(10)
memory usage: 5.5+ MB

In [24]:
df['order_date'] = pd.to_datetime(df['order_date'])

In [25]:
df.to_csv("clean_superstore.csv", index=False)

In [26]:
pwd

'C:\\Users\\jyoth'

In [27]:
df1 = pd.read_csv(r"C:\Users\jyoth\clean_superstore.csv")

In [28]:
df1

,category,city,country,customer_name,order_date,product_name,profit,quantity,region,sales,segment,state,sub_category
0,Office Supplies,Los Angeles,United States,Lycoris Saunders,2011-01-07,Xerox 225,9.3312,3,West,19,Consumer,California,Paper
1,Office Supplies,Los Angeles,United States,Mark Van Huff,2011-01-21,"Wirebound Service Call Books, 5 1/2"" x 4""",9.2928,2,West,19,Consumer,California,Paper
2,Office Supplies,Los Angeles,United States,Chad Sievert,2011-08-05,"Adams Phone Message Book, Professional, 400 Me...",9.8418,3,West,21,Consumer,California,Paper
3,Office Supplies,Los Angeles,United States,Chad Sievert,2011-08-05,Xerox 1913,53.2608,2,West,111,Consumer,California,Paper
4,Office Supplies,Los Angeles,United States,Arthur Prichep,2011-09-29,Xerox 223,3.1104,1,West,6,Consumer,California,Paper
...,...,...,...,...,...,...,...,...,...,...,...,...,...
51276,Office Supplies,Los Angeles,United States,Alice McCarthy,2014-12-03,Satellite Sectional Post Binders,22.5732,2,West,69,Corporate,California,Binders
51277,Office Supplies,Los Angeles,United States,Alice McCarthy,2014-12-03,Staples,3.1584,6,West,9,Corporate,California,Binders
51278,Office Supplies,Los Angeles,United States,Hallie Redmond,2014-12-18,GBC Plastic Binding Combs,4.2804,2,West,12,Home Office,California,Binders
51279,Office Supplies,Los Angeles,United States,Robert Marley,2014-12-25,Vinyl Sectional Post Binders,33.9300,3,West,90,Home Office,California,Binders
51280,Office Supplies,Los Angeles,United States,Fred Hopkins,2014-12-26,GBC DocuBind P50 Personal Binding Machine,51.8238,3,West,154,Corporate,California,Binders

In [32]:
import pandas as pd

df1 = pd.read_csv(r"C:\Users\jyoth\Downloads\clean_superstore3.csv", encoding="latin1")
df1.to_csv("final_clean_utf8.csv", index=False, encoding="utf-8")

In [33]:
pwd

'C:\\Users\\jyoth'

In [34]:
df2 = pd.read_csv(r"C:\Users\jyoth\final_clean_utf8.csv")

In [35]:
df2.head(2)

,ï»¿category,city,country,customer_name,order_date,product_name,profit,quantity,region,sales,segment,state,sub_category
0,Office Supplies,Los Angeles,United States,Lycoris Saunders,07-01-2011,Xerox 225,9.3312,3,West,19,Consumer,California,Paper
1,Office Supplies,Los Angeles,United States,Mark Van Huff,21-01-2011,"Wirebound Service Call Books, 5 1/2"" x 4""",9.2928,2,West,19,Consumer,California,Paper